import type { TestOutcome, TestResult } from './types.js';

export interface ScoreboardEntry {
  readonly suite: string;
  readonly test: string;
  readonly outcome: TestOutcome | 'expected-fail';
  readonly detail: string;
  /** Required for expected-fail: which subsystem owns it, and why it is not a regression. */
  readonly subsystem?: string;
  readonly reason?: string;
}

export interface Scoreboard {
  readonly generatedAt: string;
  readonly entries: readonly ScoreboardEntry[];
  readonly totals: Readonly<Record<ScoreboardEntry['outcome'], number>>;
}

/**
 * An accuracy scoreboard, committed to the repo. A diff of this file is the most
 * informative thing in any core PR.
 *
 * Moving a test into `expected-fail` requires a subsystem and a written reason — silently
 * re-baselining a regression is how accuracy rots.
 */
export function generateScoreboard(
  results: readonly (TestResult & { suite: string })[],
  expectedFailures: ReadonlyMap<string, { subsystem: string; reason: string }> = new Map(),
): Scoreboard {
  const entries: ScoreboardEntry[] = results.map((result) => {
    const expected = expectedFailures.get(`${result.suite}/${result.name}`);
    if (expected && (result.outcome === 'fail' || result.outcome === 'timeout')) {
      return {
        suite: result.suite,
        test: result.name,
        outcome: 'expected-fail',
        detail: result.detail,
        subsystem: expected.subsystem,
        reason: expected.reason,
      };
    }
    return {
      suite: result.suite,
      test: result.name,
      outcome: result.outcome,
      detail: result.detail,
    };
  });

  const totals = {
    pass: 0,
    fail: 0,
    timeout: 0,
    unavailable: 0,
    screenshot: 0,
    'expected-fail': 0,
  };
  for (const entry of entries) totals[entry.outcome]++;

  return { generatedAt: new Date().toISOString(), entries, totals };
}

const ICON: Record<ScoreboardEntry['outcome'], string> = {
  pass: '✅',
  fail: '❌',
  timeout: '⏱️',
  unavailable: '⚪',
  screenshot: '🖼️',
  'expected-fail': '🟡',
};

export function renderScoreboardMarkdown(board: Scoreboard): string {
  const t = board.totals;
  const lines = [
    '# Accuracy Scoreboard',
    '',
    '<!-- Generated by tests/harness. Do not edit by hand: `npm run scoreboard`. -->',
    '',
    `Generated: ${board.generatedAt}`,
    '',
    `**${t.pass} pass · ${t.fail} fail · ${t.timeout} timeout · ${t['expected-fail']} expected-fail · ${t.unavailable} unavailable · ${t.screenshot} screenshot**`,
    '',
    '⚪ *unavailable* means the hardware hooks the test needs do not exist yet. It is not a pass.',
    '',
    '🖼️ *screenshot* means the test is judged by comparing pixels, which this runner does not do.',
    'It is not a pass either — run `npm run screenshots` for those verdicts.',
    '',
    '| | Suite | Test | Detail |',
    '|---|---|---|---|',
  ];

  for (const e of board.entries) {
    const detail =
      e.outcome === 'expected-fail'
        ? `**${e.subsystem}** — ${e.reason}`
        : e.detail.replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(`| ${ICON[e.outcome]} | ${e.suite} | ${e.test} | ${detail} |`);
  }

  return lines.join('\n') + '\n';
}
